Repository open-dollar/od-contracts, pull requests merged in 2024-05, with the labels that each got.

#666 Add collateral sepolia test
  README.md
  gov-input/sepolia/new-AddCollateral.json
  script/gov/helpers/GovernanceHelpers.s.sol
  tasks/governanceManager.sh
Labels: ch-34

#693 Fix SafeManager Interface
  src/interfaces/proxies/IODSafeManager.sol
Labels: ch-35

#704 add allow safe call to the protectSafe function in basicActions.
  src/contracts/proxies/actions/BasicActions.sol
  test/e2e/E2ESafeManager.t.sol
Labels: ch-36
